services:
  localstack:
    image: localstack/localstack
    container_name: etl-localstack
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - AWS_DEFAULT_REGION=ap-northeast-1
    ports:
      - "4566:4566"
    networks:
      - etl-net

  db:
    image: postgres:15
    container_name: etl-postgres
    environment:
      POSTGRES_USER: etluser
      POSTGRES_PASSWORD: etlpass
      POSTGRES_DB: etldb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - etl-net

  php-scraper:
    build: ./php-scraper
    container_name: etl-php-scraper
    depends_on:
      localstack:
        condition: service_started   # ← healthy でなく started に
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: ap-northeast-1
    networks:
      - etl-net

  python-transform:
    build: ./python-transform
    container_name: etl-python-transform
    depends_on:
      localstack:
        condition: service_started
      db:
        condition: service_started
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: ap-northeast-1
    networks:
      - etl-net

networks:
  etl-net:
    driver: bridge
